import Link from "next/link";
import { ArrowLeft, CheckCircle2, ClipboardPenLine } from "lucide-react";
import { notFound } from "next/navigation";
import ActionSubmitButton from "@/components/forms/ActionSubmitButton";
import { createAdminClient } from "@/lib/supabase/admin";
import { submitPublicChurchFormAction } from "./actions";

type Props = { params: Promise<{ slug: string; token: string }>; searchParams?: Promise<{ submitted?: string; error?: string }> };
type PublicField = { key: string; label: string; type: "text" | "email" | "tel" | "textarea" | "date" | "number" | "select"; required?: boolean; options?: string[] };
const inputClass = "min-h-12 w-full rounded-2xl border border-[#DCEAF5] bg-white px-4 text-sm text-slate-800 outline-none transition focus:border-[#6D28D9] focus:ring-4 focus:ring-violet-100";

export default async function PublicRegistrationPage({ params, searchParams }: Props) {
  const { slug, token } = await params; const query = searchParams ? await searchParams : {};
  const admin = createAdminClient();
  const { data: church } = await admin.from("churches").select("id,name,public_name,slug,status,public_enabled,logo_url").eq("slug", slug).maybeSingle();
  if (!church || church.status !== "active" || church.public_enabled === false) notFound();
  const { data: form } = await admin.from("church_forms").select("id,title,description,fields,confirmation_message,status,public_enabled").eq("church_id", church.id).eq("public_token", token).maybeSingle();
  if (!form || form.status !== "published" || !form.public_enabled) notFound();
  const fields = (Array.isArray(form.fields) ? form.fields : []) as PublicField[]; const churchName = church.public_name || church.name || "Église";

  return <main className="min-h-screen bg-[#F5F9FC] px-3 py-5 sm:px-6 sm:py-10"><div className="mx-auto max-w-2xl"><Link href={`/church/${slug}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black text-[#03357A] shadow-sm"><ArrowLeft className="h-4 w-4" />Retour à l’église</Link><section className="mt-5 overflow-hidden rounded-[2rem] bg-white shadow-xl shadow-slate-200/60"><header className="bg-gradient-to-br from-[#312E81] via-[#6D28D9] to-[#A855F7] p-6 text-white sm:p-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15"><ClipboardPenLine className="h-7 w-7" /></div><p className="mt-5 text-xs font-black uppercase tracking-[0.2em] text-violet-100">{churchName}</p><h1 className="mt-2 text-3xl font-black">{form.title}</h1><p className="mt-3 text-sm leading-7 text-violet-50">{form.description || "Merci de compléter les informations ci-dessous."}</p></header><div className="p-5 sm:p-8">{query.submitted ? <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600" /><h2 className="mt-4 text-2xl font-black text-emerald-900">Réponse envoyée</h2><p className="mt-2 leading-7 text-emerald-800">{form.confirmation_message}</p></div> : <>{query.error && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">Certains champs sont incomplets ou l’envoi a échoué. Vérifiez puis réessayez.</div>}<form action={submitPublicChurchFormAction} className="space-y-5"><input type="hidden" name="church_slug" value={slug} /><input type="hidden" name="form_token" value={token} /><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true" />{fields.map((field) => <label key={field.key} className="block"><span className="mb-2 block text-sm font-black text-slate-700">{field.label}{field.required ? " *" : ""}</span>{field.type === "textarea" ? <textarea name={`answer_${field.key}`} required={field.required} maxLength={4000} className={`${inputClass} min-h-32 py-3`} /> : field.type === "select" ? <select name={`answer_${field.key}`} required={field.required} defaultValue="" className={inputClass}><option value="" disabled>Choisir…</option>{(field.options || []).map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input name={`answer_${field.key}`} type={field.type} required={field.required} maxLength={500} className={inputClass} />}</label>)}<ActionSubmitButton pendingLabel="Envoi…" className="min-h-14 w-full rounded-2xl bg-violet-600 px-6 text-base font-black text-white shadow-lg shadow-violet-200">Envoyer ma réponse</ActionSubmitButton><p className="text-center text-xs leading-5 text-slate-500">Vos informations sont transmises uniquement à {churchName}.</p></form></>}</div></section></div></main>;
}
