"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { Search, Sparkles } from "lucide-react";

type Group = { type: string; label: string; href: string; rows: Record<string, unknown>[] };
export default function ChurchSearchAssistant() {
  const [query, setQuery] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState<{summary:string;groups:Group[]}|null>(null); const [error,setError]=useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response=await fetch("/api/assistant/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})}); const payload=await response.json(); setLoading(false); if(!response.ok){setError(payload.error||"Recherche impossible.");return;} setResult(payload); }
  const title=(row:Record<string,unknown>)=>String(row.title||row.name||[row.first_name,row.last_name].filter(Boolean).join(" ")||"Résultat");
  return <div className="space-y-5"><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Ex. jeunesse, culte, offrande, tâche…" className="h-14 w-full rounded-2xl border border-[#DCEAF5] pl-12 pr-4 outline-none focus:border-[#03357A]"/></div><button disabled={loading} className="rounded-2xl bg-[#03357A] px-6 py-3 font-black text-white disabled:opacity-60">{loading?"Recherche…":"Rechercher"}</button></form>{error&&<p className="rounded-2xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}{result&&<><div className="rounded-3xl bg-gradient-to-r from-violet-50 to-blue-50 p-5"><div className="flex gap-3"><Sparkles className="h-6 w-6 text-violet-600"/><div><h2 className="font-black text-[#03357A]">Résumé intelligent</h2><p className="mt-2 text-sm leading-7 text-slate-700">{result.summary}</p></div></div></div><div className="grid gap-4 lg:grid-cols-2">{result.groups.filter(g=>g.rows.length).map(group=><section key={group.type} className="rounded-3xl border border-[#DCEAF5] bg-white p-5"><div className="flex justify-between"><h3 className="font-black text-[#03357A]">{group.label}</h3><Link href={group.href} className="text-sm font-bold text-blue-600">Ouvrir</Link></div><div className="mt-3 space-y-2">{group.rows.map((row,index)=><div key={String(row.id||index)} className="rounded-xl bg-[#F8FBFD] p-3"><p className="font-bold text-slate-800">{title(row)}</p><p className="mt-1 text-xs text-slate-500">{String(row.status||row.event_date||row.transaction_date||"")}</p></div>)}</div></section>)}</div></>}</div>;
}
