import { CheckCircle2, ClipboardList, ExternalLink, FilePlus2, Inbox } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import MetricCard from "@/components/dashboard/MetricCard";
import ActionSubmitButton from "@/components/forms/ActionSubmitButton";
import { requireChurchModuleAccess } from "@/lib/modules/moduleAccess";
import { createChurchFormAction, updateFormStatusAction, updateSubmissionStatusAction } from "./actions";

type Query = Promise<{ saved?: string; error?: string }>;
type ChurchForm = { id: string; title: string; description: string | null; public_token: string; form_type: string; fields: Array<{ key: string; label: string; type: string; required: boolean }>; status: string; created_at: string };
type Submission = { id: string; form_id: string; respondent_name: string | null; respondent_email: string | null; respondent_phone: string | null; answers: Record<string, string>; status: string; created_at: string };
const inputClass = "min-h-12 w-full rounded-2xl border border-[#DCEAF5] bg-white px-4 text-sm text-slate-800 outline-none transition focus:border-[#2563EB] focus:ring-4 focus:ring-blue-100";

export default async function FormsPage({ searchParams }: { searchParams?: Query }) {
  const params = searchParams ? await searchParams : {};
  const { admin, profile, permissions } = await requireChurchModuleAccess("custom_forms");
  const [formsResult, submissionsResult, churchResult] = await Promise.all([
    admin.from("church_forms").select("id,title,description,public_token,form_type,fields,status,created_at").eq("church_id", profile.church_id).neq("status", "archived").order("created_at", { ascending: false }),
    admin.from("church_form_submissions").select("id,form_id,respondent_name,respondent_email,respondent_phone,answers,status,created_at").eq("church_id", profile.church_id).neq("status", "archived").order("created_at", { ascending: false }).limit(100),
    admin.from("churches").select("slug").eq("id", profile.church_id).maybeSingle(),
  ]);
  const forms = (formsResult.data || []) as ChurchForm[];
  const submissions = (submissionsResult.data || []) as Submission[];
  const churchSlug = churchResult.data?.slug || "";
  const formNames = new Map(forms.map((form) => [form.id, form.title]));

  return <AppShell><div className="space-y-6 pb-24 md:pb-0">
    <section className="rounded-[1.75rem] bg-gradient-to-br from-[#312E81] via-[#6D28D9] to-[#A855F7] p-5 text-white shadow-xl shadow-violet-950/15 sm:p-7"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15"><ClipboardList className="h-7 w-7" /></div><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-violet-100">Collecte & inscriptions</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Formulaires publics</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-violet-50">Créez une inscription en quelques lignes, partagez son lien et traitez les réponses depuis un seul endroit.</p></div></div></section>
    {params.saved && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Modification enregistrée avec succès.</div>}
    {params.error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">L’opération n’a pas abouti. Vérifiez le formulaire puis réessayez.</div>}
    {(formsResult.error || submissionsResult.error) && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">Le module doit encore être initialisé dans la base de données.</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Formulaires" value={forms.length} description="Créés pour cette église" icon={ClipboardList} accent="purple" /><MetricCard title="Publiés" value={forms.filter((item) => item.status === "published").length} description="Accessibles au public" icon={ExternalLink} accent="blue" /><MetricCard title="Nouvelles réponses" value={submissions.filter((item) => item.status === "new").length} description="À traiter" icon={Inbox} accent="orange" /><MetricCard title="Validées" value={submissions.filter((item) => item.status === "approved").length} description="Réponses approuvées" icon={CheckCircle2} accent="green" /></section>

    {permissions.can_create && <section className="rounded-3xl border border-[#DCEAF5] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><FilePlus2 className="h-6 w-6 text-violet-600" /><h2 className="text-xl font-black text-[#03357A]">Créer un formulaire</h2></div><form action={createChurchFormAction} className="mt-5 grid gap-4 md:grid-cols-2">
      <input name="title" required maxLength={160} placeholder="Titre du formulaire" className={inputClass} /><select name="form_type" defaultValue="general" className={inputClass}><option value="general">Général</option><option value="event">Événement</option><option value="group">Groupe</option><option value="volunteer">Bénévolat</option><option value="counseling">Accompagnement</option></select>
      <textarea name="description" maxLength={1500} placeholder="Description affichée au public" className={`${inputClass} min-h-28 py-3 md:col-span-2`} />
      <div className="md:col-span-2"><label className="text-sm font-black text-slate-700">Questions, une par ligne</label><p className="mt-1 text-xs leading-5 text-slate-500">Format : Libellé | type | obligatoire. Types : text, email, tel, textarea, date, number, select. Pour un choix : ajoutez | Option A, Option B.</p><textarea name="fields_definition" required defaultValue={"Nom complet | text | obligatoire\nTéléphone | tel | obligatoire\nVotre message | textarea"} className={`${inputClass} mt-2 min-h-36 py-3 font-mono`} /></div>
      <input name="confirmation_message" maxLength={500} defaultValue="Merci, votre réponse a bien été enregistrée." className={`${inputClass} md:col-span-2`} />
      <label className="flex min-h-12 items-center gap-3 rounded-2xl border border-[#DCEAF5] px-4 text-sm font-bold text-slate-700 md:col-span-2"><input name="publish" type="checkbox" defaultChecked />Publier et rendre le lien accessible immédiatement</label>
      <ActionSubmitButton pendingLabel="Création…" className="min-h-12 rounded-2xl bg-violet-600 px-5 text-sm font-black text-white md:col-span-2">Créer le formulaire</ActionSubmitButton>
    </form></section>}

    <section className="grid gap-4 xl:grid-cols-2">{forms.length === 0 && <div className="rounded-3xl border border-dashed border-[#DCEAF5] bg-white p-10 text-center text-sm text-slate-500 xl:col-span-2">Aucun formulaire pour le moment.</div>}{forms.map((form) => {
      const count = submissions.filter((item) => item.form_id === form.id).length; const publicPath = `/registration/${form.public_token}`;
      return <article key={form.id} className="rounded-3xl border border-[#DCEAF5] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600">{form.form_type}</p><h2 className="mt-1 text-xl font-black text-[#03357A]">{form.title}</h2></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-black text-violet-700">{count} réponse(s)</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{form.description || "Aucune description."}</p><div className="mt-4 rounded-2xl bg-[#F7FAFC] p-3"><p className="text-xs font-bold text-slate-500">Lien à partager</p><a href={publicPath} target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-2 break-all text-sm font-black text-blue-700 hover:underline"><ExternalLink className="h-4 w-4 shrink-0" />{churchSlug ? `https://${churchSlug}.mpangi-church.app${publicPath}` : publicPath}</a></div>{permissions.can_update && <form action={updateFormStatusAction} className="mt-4 flex gap-2"><input type="hidden" name="form_id" value={form.id} /><select name="status" defaultValue={form.status} className={inputClass}><option value="draft">Brouillon</option><option value="published">Publié</option><option value="closed">Fermé</option></select><ActionSubmitButton pendingLabel="…" className="min-h-12 rounded-2xl bg-[#03357A] px-4 text-sm font-black text-white">Mettre à jour</ActionSubmitButton></form>}</article>;
    })}</section>

    <section className="rounded-3xl border border-[#DCEAF5] bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-black text-[#03357A]">Réponses récentes</h2><div className="mt-5 space-y-3">{submissions.length === 0 && <p className="rounded-2xl bg-[#F7FAFC] p-6 text-center text-sm text-slate-500">Aucune réponse reçue.</p>}{submissions.map((submission) => <article key={submission.id} className="rounded-2xl border border-[#E8F0F6] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-[#03357A]">{submission.respondent_name || "Réponse anonyme"}</p><p className="mt-1 text-xs text-slate-500">{formNames.get(submission.form_id) || "Formulaire"} · {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(submission.created_at))}</p><p className="mt-1 text-xs text-slate-500">{submission.respondent_phone || submission.respondent_email || "Aucun contact"}</p></div>{permissions.can_update && <form action={updateSubmissionStatusAction} className="flex gap-2"><input type="hidden" name="submission_id" value={submission.id} /><select name="status" defaultValue={submission.status} className="min-h-10 rounded-xl border border-[#DCEAF5] bg-white px-3 text-xs font-bold"><option value="new">Nouvelle</option><option value="reviewing">En traitement</option><option value="approved">Validée</option><option value="rejected">Refusée</option><option value="archived">Archivée</option></select><ActionSubmitButton pendingLabel="…" className="min-h-10 rounded-xl bg-violet-600 px-3 text-xs font-black text-white">OK</ActionSubmitButton></form>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(submission.answers || {}).slice(0, 8).map(([key, value]) => <p key={key} className="rounded-xl bg-[#F7FAFC] px-3 py-2 text-xs text-slate-700"><span className="font-black">{key.replace(/^field_\d+:/, "")}</span> {String(value)}</p>)}</div></article>)}</div></section>
  </div></AppShell>;
}
