import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, Download, ExternalLink, FileText, Lock, UserRound } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import { getDocumentDownloadHref } from "@/lib/storage/churchDocuments";
import { requireChurchModuleAccess } from "@/lib/modules/moduleAccess";
import { updateCorrespondenceStatusAction } from "../actions";

type Props = { params: Promise<{ id: string }> };
const TYPE: Record<string,string> = { incoming: "Courrier entrant", outgoing: "Courrier sortant", internal: "Courrier interne" };
const STATUS: Record<string,string> = { draft: "Brouillon", received: "Reçu", sent: "Envoyé", in_review: "En traitement", transmitted: "Transmis", closed: "Clôturé", archived: "Archivé" };
const PRIORITY: Record<string,string> = { low: "Faible", normal: "Normale", high: "Haute", urgent: "Urgente" };

function formatDate(v?: string | null) { if (!v) return "-"; try { return new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(v)); } catch { return String(v); } }
function formatSize(v?: number | null) { if (!v) return "-"; return v < 1024*1024 ? `${Math.round(v/1024)} Ko` : `${(v/1024/1024).toFixed(1)} Mo`; }

export default async function CorrespondenceDetailPage({ params }: Props) {
  const { id } = await params;
  const { admin, profile } = await requireChurchModuleAccess("correspondence");
  const { data: c } = await admin.from("admin_correspondences").select(`*, departments(name), assigned_profile:profiles!admin_correspondences_assigned_to_fkey(full_name, role)`).eq("church_id", profile.church_id).eq("id", id).maybeSingle();
  if (!c) notFound();

  return <AppShell><div className="space-y-6">
    <Link href="/administration/correspondence" className="inline-flex items-center gap-2 text-sm font-bold text-[#2563EB]"><ArrowLeft className="h-4 w-4"/>Retour aux courriers</Link>
    <section className="rounded-3xl bg-gradient-to-br from-[#03357A] via-[#2563EB] to-[#8B5CF6] p-6 text-white shadow-lg shadow-blue-900/20"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-100">{TYPE[c.type] || c.type}</p><h1 className="mt-3 text-3xl font-extrabold">{c.subject}</h1><p className="mt-2 text-sm leading-7 text-blue-50">Référence : {c.reference} · Date : {formatDate(c.correspondence_date)}</p></div><div className="rounded-2xl bg-white/15 px-5 py-4 text-center ring-1 ring-white/20"><p className="text-lg font-black">{STATUS[c.status] || c.status}</p><p className="text-xs font-bold uppercase tracking-wide text-blue-100">Statut actuel</p></div></div></section>
    <section className="grid gap-4 md:grid-cols-4"><Info label="Priorité" value={PRIORITY[c.priority] || c.priority} icon={Lock}/><Info label="Date courrier" value={formatDate(c.correspondence_date)} icon={CalendarDays}/><Info label="Date limite" value={formatDate(c.due_date)} icon={CalendarDays}/><Info label="Département" value={c.departments?.name || "-"} icon={UserRound}/></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><div className="rounded-3xl border border-[#DCEAF5] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold text-[#03357A]">Informations du courrier</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Detail label="Expéditeur" value={c.sender_name}/><Detail label="Contact expéditeur" value={c.sender_contact}/><Detail label="Destinataire" value={c.recipient_name}/><Detail label="Contact destinataire" value={c.recipient_contact}/><Detail label="Responsable assigné" value={c.assigned_profile?.full_name || c.assigned_profile?.role || "-"}/><Detail label="Confidentiel" value={c.confidential ? "Oui" : "Non"}/></div>
      <div className="mt-6 rounded-3xl border border-[#DCEAF5] bg-[#F8FBFD] p-5"><h3 className="font-extrabold text-[#03357A]">Document joint</h3>{c.document_path ? <div className="mt-4 flex flex-col gap-3 rounded-2xl bg-white p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-extrabold text-slate-800">{c.document_name || "Document"}</p><p className="mt-1 text-sm text-slate-500">{c.document_mime_type || "Fichier"} · {formatSize(c.document_size)}</p></div><a href={getDocumentDownloadHref({ path: c.document_path, filename: c.document_name || c.reference })} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#03357A] px-5 py-3 text-sm font-extrabold text-white"><Download className="h-4 w-4"/>Télécharger</a></div> : <p className="mt-3 text-sm text-slate-500">Aucun fichier chargé.</p>}{c.document_url && <a href={c.document_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 rounded-2xl bg-[#EAF3FA] px-4 py-3 text-sm font-extrabold text-[#03357A]"><ExternalLink className="h-4 w-4"/>Ouvrir le lien externe</a>}</div>
      <div className="mt-6 rounded-2xl bg-[#F8FBFD] p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Notes internes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{c.notes || "Aucune note."}</p></div></div>
      <div className="rounded-3xl border border-[#DCEAF5] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#EAF3FA] text-[#03357A]"><FileText className="h-5 w-5" /></div><div><h2 className="text-xl font-extrabold text-[#03357A]">Mise à jour du statut</h2><p className="text-sm text-slate-500">Changez le statut selon l’avancement.</p></div></div><form action={updateCorrespondenceStatusAction} className="mt-5 space-y-4"><input type="hidden" name="id" value={c.id}/><select name="status" defaultValue={c.status} className="min-h-12 w-full rounded-2xl border border-[#DCEAF5] bg-white px-4 text-sm font-semibold text-slate-700 outline-none focus:border-[#03357A] focus:ring-4 focus:ring-[#03357A]/10"><option value="draft">Brouillon</option><option value="received">Reçu</option><option value="sent">Envoyé</option><option value="in_review">En traitement</option><option value="transmitted">Transmis</option><option value="closed">Clôturé</option><option value="archived">Archivé</option></select><button type="submit" className="w-full rounded-2xl bg-[#03357A] px-5 py-3 text-sm font-extrabold text-white">Mettre à jour</button></form></div></section>
  </div></AppShell>;
}
function Info({ label, value, icon: Icon }: { label: string; value: string; icon: any }) { return <div className="rounded-3xl border border-[#DCEAF5] bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-[#03357A]"/><p className="mt-4 text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-extrabold text-[#03357A]">{value}</p></div>; }
function Detail({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-2xl border border-[#DCEAF5] bg-[#F8FBFD] p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-700">{value || "-"}</p></div>; }
